import {
  ArrowLeftRight,
  BookOpen,
  Boxes,
  CircleCheckBig,
  Database,
  FileText,
  Flag,
  FolderGit2,
  FolderKanban,
  GitBranch,
  Hourglass,
  Info,
  Layers,
  LayoutGrid,
  Lightbulb,
  ListOrdered,
  Package,
  Play,
  Plug,
  ScrollText,
  Signpost,
  Sparkle,
  Sparkles,
  SquareCheck,
  Star,
  UserRound,
  Wrench,
  type LucideIcon
} from 'lucide-react'
import type { NodeIconKey } from './nodeVisual'

/**
 * Pictogramme du type d'un nœud (spec 022 D11, D12) : bibliothèque Lucide, imports nommés (seules ces icônes sont
 * embarquées). Toujours décoratif (`aria-hidden`) : le type est aussi dans le nom accessible du nœud.
 */
export const NODE_ICONS: Readonly<Record<NodeIconKey, LucideIcon>> = {
  step: ListOrdered,
  idea: Lightbulb,
  document: FileText,
  final: Flag,
  deliverable: Package,
  module: Boxes,
  component: LayoutGrid,
  data: Database,
  task: SquareCheck,
  family: GitBranch,
  skillPerso: Sparkles,
  skillProjet: FolderGit2,
  skillPlugin: Plug,
  project: FolderKanban,
  you: UserRound,
  feature: Star,
  interface: ArrowLeftRight,
  decision: Signpost,
  operation: Wrench,
  branchActive: Play,
  branchUpcoming: Hourglass,
  branchDelivered: CircleCheckBig,
  branchBrainstorm: Sparkle,
  spec: ScrollText,
  story: BookOpen,
  socle: Layers,
  info: Info
}
